stages:
  - tests
  - report

variables:
  STAGE: prod

services:
  - docker:24.0.5-dind

run_tests:
    stage: tests
    when: manual
    image: docker:24.0.5
#    before_script:
#      - apk add curl jq
#      - ARTIFACTS_CHECK_URL="https://$CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages&private_token=$PRIVATE_TOKEN"
#      - curl -k --location --output artifacts.zip $ARTIFACTS_CHECK_URL
#      - unzip artifacts.zip
#      - chmod -R 777 public
#      - mkdir -p allure-results && cp -r public/history allure-results
    script:
        - docker-compose up api-tests || true
    after_script:
        - docker-compose up report
        - ls -la allure-report
    artifacts:
      paths:
          - allure-report
      when: always

pages:
  stage: report
  needs:
    - run_tests
  script:
    - mv allure-report public
    - ls -la public
  artifacts:
    when: on_success
    expire_in: never
    paths:
      - public
      - allure-report

#notification:
#  stage: report
#  needs:
#    - pages
#  image: docker:24.0.5
#  script:
#    - docker-compose up notification