version: "3.7"

services:
  api-tests:
    image: api-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      STAGE: prod
      SUITE: users
      API_TOKEN: ${API_TOKEN}
    working_dir: /usr/workspace
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "STAGE=$$STAGE pytest -sv --alluredir=allure-results"



  report:
    image: api-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/workspace
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "allure generate allure-results -o allure-report"


  notification:
    image: api-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TG_TOKEN: ${TG_TOKEN}
      CHAT_ID: ${CHAT_ID}
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace/notification
    command: /bin/sh -c "python notification.py --config_file=base.json"
